import { notFound } from 'next/navigation'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
const ARTIGOS: Record<string,{title:string,cat:string,date:string,subtitle:string,img:string,body:string}> = {
  'metodo-calix-etica-performance':{title:'Método Calix: por que ética e performance não são opostos',cat:'Investimentos',date:'Janeiro de 2026',subtitle:'Como nossa metodologia gera resultados superiores no longo prazo.',img:'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1400&q=80&auto=format',body:'<p>Existe um equívoco comum no mercado financeiro: a ideia de que investir com critérios éticos significa abrir mão de rentabilidade. Na Calix, discordamos profundamente.</p><h2>A origem do <em>Método Calix</em></h2><p>O Método Calix nasceu de uma convicção simples: empresas com boa governança tendem a ser mais resilientes e lucrativas no longo prazo.</p><div class="art-pullquote"><p>"Empresas que passam pelo nosso filtro apresentam menor volatilidade e maior previsibilidade de resultados."</p></div>'},
  'governanca-familiar-sucessao':{title:'Governança familiar: como estruturar a sucessão sem conflitos',cat:'Sucessão',date:'Fevereiro de 2026',subtitle:'Os principais erros das famílias empresárias no processo sucessório.',img:'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1400&q=80&auto=format',body:'<p>A sucessão patrimonial e empresarial é um dos momentos mais delicados na vida de uma família. Quando mal planejada, pode destruir o que levou gerações para construir.</p><div class="art-pullquote"><p>"Questões sucessórias discutidas na crise são sempre mais caras e dolorosas do que quando planejadas com antecedência."</p></div>'},
  'trusts-offshores-quando-faz-sentido':{title:'Trusts e offshores: quando faz sentido para sua família',cat:'Offshore',date:'Março de 2026',subtitle:'Um guia objetivo sobre proteção patrimonial no exterior.',img:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1400&q=80&auto=format',body:'<p>A internacionalização patrimonial deixou de ser exclusividade de grandes fortunas. Com a crescente instabilidade regulatória e cambial no Brasil, famílias de diferentes portes buscam diversificação.</p><div class="art-pullquote"><p>"Planejamento tributário legítimo é diferente de evasão fiscal — e na Calix, trabalhamos exclusivamente dentro da legalidade."</p></div>'},
}
export async function generateStaticParams(){return Object.keys(ARTIGOS).map(slug=>({slug}))}
export default function ArtigoPage({params}:{params:{slug:string}}){
  const a=ARTIGOS[params.slug]; if(!a)notFound()
  return (<><style>{`.art-layout{padding-top:72px}.art-hero{position:relative;height:500px;overflow:hidden}.art-hero img{width:100%;height:100%;object-fit:cover;filter:brightness(.48) saturate(.5)}.art-hero-overlay{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:flex-end;padding:56px 5vw}.art-cat-tag{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:.24em;text-transform:uppercase;color:#b5caaa;border:1px solid rgba(181,202,170,.28);padding:5px 14px;display:inline-block;margin-bottom:1.2rem}.art-hero-title{font-family:'Lora',serif;font-size:clamp(26px,4.5vw,56px);font-weight:400;color:#dbd6c1;line-height:1.15;max-width:820px}.art-hero-sub{font-size:17px;font-weight:300;color:rgba(219,214,193,.7);margin-top:1.2rem;max-width:680px;line-height:1.7}.art-wrapper{display:grid;grid-template-columns:1fr min(800px,90%) 1fr}.art-wrapper>*{grid-column:2}.art-content{padding:64px 0 90px}.art-content h2{font-family:'Lora',serif;font-size:27px;font-weight:400;color:#111a1b;margin:3.5rem 0 1.4rem;line-height:1.3}.art-content h2 em{font-style:italic}.art-content p{font-size:18px;font-weight:300;line-height:2;color:#222;margin-bottom:1.5rem}.art-pullquote{border-left:3px solid #b5caaa;padding:1.4rem 2rem;margin:2.5rem 0;background:rgba(181,202,170,.05)}.art-pullquote p{font-family:'Lora',serif;font-size:22px;font-style:italic;color:#192627;line-height:1.65;font-weight:400;margin:0}@media(max-width:900px){.art-wrapper{grid-template-columns:1fr;padding:0 1.4rem}.art-wrapper>*{grid-column:1}.art-hero{height:380px}.art-hero-overlay{padding:36px 1.4rem}}`}</style>
    <Nav/><div className="art-layout">
      <div className="art-hero"><img src={a.img} alt={a.title}/><div className="art-hero-overlay"><span className="art-cat-tag">{a.cat} · {a.date}</span><h1 className="art-hero-title">{a.title}</h1><p className="art-hero-sub">{a.subtitle}</p></div></div>
      <div className="art-wrapper"><div className="art-content"><div dangerouslySetInnerHTML={{__html:a.body}}/><div style={{background:'#111a1b',padding:'2.8rem',marginTop:'3.5rem'}}><h3 style={{fontFamily:'Lora,serif',fontSize:'22px',fontWeight:400,color:'#dbd6c1',lineHeight:1.3,marginBottom:'.5rem'}}>Quer aprofundar esse tema com <em style={{fontStyle:'italic',color:'#b5caaa'}}>especialistas</em>?</h3><p style={{fontSize:'15px',fontWeight:300,color:'rgba(219,214,193,.6)',marginBottom:'1.5rem'}}>Uma conversa inicial, sem compromisso.</p><a href="https://wa.me/5511958649091" target="_blank" rel="noopener noreferrer" className="btn-sage">Falar com a Calix</a></div></div></div>
    </div><Footer/></>)
}
